- name: Create Folders
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item.name}}"
    password: admin123
    url: http://172.31.92.24:8080
    user: admin
  loop:
    - { name: "ci-pipelines"}
